stages:
  - build
  - publish

variables:
  HELM_REPO_CHANNEL: "stable"
  HELM_IMAGE_TAG: "3.17"

# Execute lint checks
# if the chart is modified
.helm:lint:
  stage: build
  image:
    name: alpine/helm:${HELM_IMAGE_TAG}
    entrypoint: [""]
  script:
    - helm lint ${CHART_DIRECTORY}
  rules:
    - changes:
        - ${CHART_DIRECTORY}/*

helm:lint:hopskotch:
  extends:
    - .helm:lint
  variables:
    CHART_DIRECTORY: hopskotch

helm:lint:gracedb:
  extends:
    - .helm:lint
  variables:
    CHART_DIRECTORY: gracedb


# These steps build the Helm chart package
# and upload it to the helm-charts repo
# only when a tag is created
.helm:build:
  stage: build
  image:
    name: alpine/helm:${HELM_IMAGE_TAG}
    entrypoint: [""]
  script:
    - helm package ${CHART_DIRECTORY} --version ${CI_COMMIT_TAG}
  artifacts:
    paths:
      - ${CHART_DIRECTORY}-${CI_COMMIT_TAG}.tgz
  only:
    - tags

helm:build:hopskotch:
  extends:
    - .helm:build
  variables:
    CHART_DIRECTORY: hopskotch
  needs:
    - job: helm:lint:hopskotch


helm:build:gracedb:
  extends:
    - .helm:build
  variables:
    CHART_DIRECTORY: gracedb
  needs:
    - job: helm:lint:gracedb

.helm:publish:
  stage: publish
  image:
    name: alpine/curl:latest
    entrypoint: [""]
  script:
    - curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@${CHART_DIRECTORY}-${CI_COMMIT_TAG}.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/${HELM_REPO_CHANNEL}/charts"
  only:
    - tags

helm:publish:hopskotch:
  extends:
    - .helm:publish
  variables:
    CHART_DIRECTORY: hopskotch
  needs:
    - job: helm:build:hopskotch
      artifacts: true

helm:publish:gracedb:
  extends:
    - .helm:publish
  variables:
    CHART_DIRECTORY: gracedb
  needs:
    - job: helm:build:gracedb
      artifacts: true
