apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hopskotch.fullname" . }}-create-topics
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: create-topics
        image: "{{ .Values.image.repository | default "scimma/server" }}:{{ .Values.image.tag | default "latest" }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        command: 
          - sh
          - -c
          - |
            cp /root/create-topics.sh .
            chmod +x create-topics.sh 
            ./create-topics.sh {{ .Release.Namespace }} {{ include "hopskotch.fullname" . }}
        resources:
          limits:
            cpu: "2000m"
            memory: "1G"
          requests:
            cpu: "100m"
            memory: "200Mi"
        volumeMounts:
          - name: create-topics-script
            mountPath: /root/create-topics.sh
            subPath: create-topics.sh
          - name: topics-list
            mountPath: /tmp/topics.txt
            subPath: topics.txt
      volumes:
      - name: create-topics-script
        configMap:
          name: create-topics-script
      - name: topics-list
        configMap:
          name: topics-list
      restartPolicy: Never
  backoffLimit: 10
