apiVersion: v1
kind: Service
metadata:
  name: {{ include "hopskotch.fullname" . }}
  labels:
    {{- include "hopskotch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  ports:
    - port: 9092
      targetPort: port1
      protocol: TCP
      name: port1
  {{ if .Values.service.externalIP }}
  externalIPs:
          - {{ .Values.service.externalIP }}
  {{ end }}
  selector:
    {{- include "hopskotch.selectorLabels" . | nindent 4 }}
