apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "gracedb.fullname" . }}
spec:
  serviceName: {{ include "gracedb.fullname" . }}
  {{ if .Values.distributed.enabled }}
  replicas: {{ .Values.gracedb.replicaCount }}
  {{ else }}
  replicas: 1
  {{ end }}
  selector:
    matchLabels:
      app: {{ include "gracedb.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "gracedb.fullname" . }}
        app.kubernetes.io/part-of: gracedb
      # This is needed to restart the pod when the configmap is changed
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
    spec:
      hostname: {{ include "gracedb.fullname" . }}
      securityContext:
        seLinuxOptions:
          level: "s0:c123,c456"
      affinity:
        {{- if not .Values.distributed.enabled }}
        # Prefer scheduling of DB and webserver in the same node
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/part-of: gracedb
                topologyKey: kubernetes.io/hostname
        {{- end }}
        # In case of distributed deployment,
        # schedule replicas on different hosts.
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ include "gracedb.fullname" . }}
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ include "gracedb.fullname" . }}
          resources:
            requests:
              cpu: {{ .Values.gracedb.resources.cpu }}
              memory: {{ .Values.gracedb.resources.memory }}
            limits:
              cpu: {{ .Values.gracedb.resources.cpu }}
              memory: {{ .Values.gracedb.resources.memory }}
          image: {{ .Values.gracedb.image }}
          imagePullPolicy: {{ .Values.gracedb.pullPolicy | quote}}
          #args:
          #  - sh
          #  - -c
          #  - |
          #    #pip3 uninstall -y pyasn1 &&
          #    #pip3 install --upgrade sentry-sdk &&
          #    /usr/local/bin/supervisord -c /etc/supervisor/supervisord.conf
          envFrom: &gracedb-env-from
            - configMapRef:
                name: env
            - secretRef:
                name: {{ include "gracedb.fullname" . }}-postgres
            - secretRef:
                name: {{ include "gracedb.fullname" . }}
            {{- if .Values.gracedb.igwnAlertAuth }}
            - secretRef:
                name: igwn-alert-credentials
            {{ end }}
          env: &gracedb-env
            - name: ENABLE_SANDBOXED
              value: "{{ .Values.sandboxed.enabled }}"
            - name: ENABLE_SHIBD
              value: "false"
            - name: ENABLE_IGWN_OVERSEER
              value: "{{ .Values.alerts.igwn }}"
            - name:  IGWN_ALERT_AUTH
              value: "{{ .Values.gracedb.igwnAlertAuth }}"
            - name: DJANGO_PRIMARY_FQDN
              value: {{ .Values.publicName }}
            - name: DJANGO_ALLOWED_HOSTS
              value: {{ include "gracedb.fullname" . }}
          volumeMounts: &volumeMounts
            - name: remove-mdc-events
              mountPath: /app/gracedb_project/gracedb/events/management/commands/remove_mdc_events.py
              subPath: remove_mdc_events.py
            - name: django-base-settings
              mountPath: /app/gracedb_project/config/settings/container/base.py
              subPath: base.py
            - name: django-settings
              mountPath: /app/gracedb_project/config/settings/container/generic-test.py
              subPath: generic-test.py
            - name: django-update-site
              mountPath: /app/gracedb_project/gracedb/migrations/sites/0002_update_site.py
              subPath: 0002_update_site.py
            - name: db-data
              mountPath: "/app/db_data"
            - name: igwn-alert-overseer
              mountPath: /usr/local/bin/igwn_alert_overseer
              subPath: igwn_alert_overseer
            - name: igwn-alert-supervisor
              mountPath: /etc/supervisor/conf.d/igwn-overseer.conf
              subPath: igwn-overseer.conf
            {{ if .Values.sandboxed.enabled }}
            - name: gracedb-urls-patched
              mountPath: /app/gracedb_project/config/urls.py
              subPath: urls.py
            - name: login-template
              mountPath: /app/gracedb_project/gracedb/templates/ligoauth/login.html
              subPath: login.html
            - name: get-user
              mountPath: /app/gracedb_project/gracedb/ligoauth/management/commands/get_or_edit_account.py
              subPath: get_or_edit_account.py
            {{ end }}
          livenessProbe:
            httpGet:
              path: /heartbeat/
              port: 80
              httpHeaders:
                - name: Host
                  value: {{ include "gracedb.fullname" . }}
            failureThreshold: 2
            initialDelaySeconds: 1000
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /heartbeat/
              port: 80
              httpHeaders:
                - name: Host
                  value: {{ include "gracedb.fullname" . }}
            initialDelaySeconds: 5
            periodSeconds: 5

      initContainers:
        - name: gracedb-init
          image: {{ .Values.gracedb.image }}
          imagePullPolicy: {{ .Values.gracedb.pullPolicy | quote}}
          command:
            - sh
            - -c
            - |
              /bin/chown gracedb:www-data /app/db_data &&
              /bin/chmod 0755 /app/db_data
          securityContext:
             runAsUser: 0
          volumeMounts:
            - name: db-data
              mountPath: "/app/db_data"

        # Wait for postgres db to be ready
        - name: postgres-wait
          image: {{ .Values.postgres.image }}
          envFrom: *gracedb-env-from
          command:
            - /bin/sh
            - -c
            - >
              set -x;
              while ! pg_isready -h $DJANGO_DB_HOST -d $DJANGO_DB_NAME; do
                sleep 5;
              done

        # Run GraceDB django migrations (needs to run for new versions in
        # order for labels to be present)
        - name: gracedb-migrate
          image: {{ .Values.gracedb.image }}
          imagePullPolicy: {{ .Values.gracedb.pullPolicy | quote}}
          command:
            - /bin/sh
            - -c
            - >
              set -x;
              python3 manage.py migrate
              && python3 manage.py createcachetable
              && ([
              $(python3 manage.py shell -c "from django.contrib.auth import get_user_model; import os; print(len(get_user_model().objects.all().filter(username=os.getenv(\"DJANGO_SUPERUSER_USERNAME\"))))")
              -eq 1 ] || python3 manage.py createsuperuser --noinput)
          envFrom: *gracedb-env-from
          env: *gracedb-env
          volumeMounts: *volumeMounts

      volumes:
        - name: remove-mdc-events
          configMap:
              name: remove-mdc-events
        - name: django-base-settings
          configMap:
              name: django-base-settings
        - name: django-settings
          configMap:
              name: django-settings
        - name: django-update-site
          configMap:
              name: django-update-site
        - name: igwn-alert-overseer
          configMap:
              name: igwn-alert-overseer
              defaultMode: 0755
        - name: igwn-alert-supervisor
          configMap:
              name: igwn-alert-supervisor
        {{ if .Values.distributed.enabled }}
        - name: db-data
          persistentVolumeClaim:
            claimName: {{ .Values.gracedb.pvcName }}
        {{ end }}
        {{ if .Values.sandboxed.enabled }}
        - name: gracedb-urls-patched
          configMap:
              name: gracedb-urls-patched
        - name: login-template
          configMap:
              name: login-template
        - name: get-user
          configMap:
              name: get-user
        {{ end }}
  {{ if not .Values.distributed.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.gracedb.storage.capacity }}
        storageClassName: {{ .Values.storageClassName }}
  {{ end }}
