---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gracedb.fullname" . }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
  - name: p1
    port: 8080
  - name: p2
    port: 8001
  - name: postgres
    port: 5432
  selector:
    app: {{ include "gracedb.fullname" . }}
---
{{ if not .Values.sandboxed.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gracedb.fullname" . }}-shibd
{{ if .Values.traefik.enabled }}
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: "shibd-backend"
{{ end }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
  - name: p1
    port: 8080
  selector:
    app: {{ include "gracedb.fullname" . }}-shibd
{{ end }}
