{{ if .Values.traefik.version2.enabled }}
apiVersion: traefik.containo.us/v1alpha1
{{ else }}
apiVersion: traefik.io/v1alpha1
{{ end }}
kind: Middleware
metadata:
  name: client-cert
spec:
  passTLSClientCert:
    pem: true
    info:
      notAfter: true
      notBefore: true
      sans: true
      subject:
        country: true
        province: true
        locality: true
        organization: true
        commonName: true
        serialNumber: true
        domainComponent: true
      issuer:
        country: true
        province: true
        locality: true
        organization: true
        commonName: true
        serialNumber: true
        domainComponent: true
---
{{ if .Values.traefik.version2.enabled }}
apiVersion: traefik.containo.us/v1alpha1
{{ else }}
apiVersion: traefik.io/v1alpha1
{{ end }}
kind: TLSOption
metadata:
  name: client-auth
spec:
  clientAuth:
    clientAuthType: VerifyClientCertIfGiven
    secretNames:
    - client-ca
  #sniStrict: false
  minVersion: VersionTLS12
---
{{ if .Values.traefik.version2.enabled }}
apiVersion: traefik.containo.us/v1alpha1
{{ else }}
apiVersion: traefik.io/v1alpha1
{{ end }}
kind: TLSStore
metadata:
  name: gracedb
spec:
  defaultCertificate:
    secretName: gracedb-cert-tls
