dependencies:
- name: memcached
  version: 6.10.1
  repository: oci://registry-1.docker.io/bitnamicharts
  alias: memcached
- name: postgresql
  version: 14.0.5
  repository: oci://registry-1.docker.io/bitnamicharts
  alias: postgresql
  condition: distributed.enabled
- name: cert-manager
  version: v1.16.2
  repository: https://charts.jetstack.io
  alias: cert-manager
  condition: cert_manager.install
- name: traefik
  version: 27.0.2
  repository: https://traefik.github.io/charts
  alias: traefik
  condition: traefik.install
