# Values starting with & are anchors to be used later in this file,
# please do not change them!

traefik:
  install: true
  service:
    spec:
      clusterIP: 10.100.100.10


cert_manager:
  # Enable CRD-based automatic in-cluster certificate generation using
  # cert-manager.io operator (requires the operator and CRDs to be already
  # present in the cluster)
  enabled: true
  install: true
  # A custom cert-manager issuer can also be specified:
  # e.g.
  # issuer:
  #   name: my-ca-issuer
  #   kind: Issuer / kind: ClusterIssuer


# If true, deploy a distributed version of GraceDB and PostgreSQL.
# If false, deploy a single-node instance of GraceDB and PostgreSQL.
distributed:
  enabled: false

# If true, deploy a sandboxed version of GraceDB (required for Minikube)
# If false, deploy the official instance of GraceDB
sandboxed:
  enabled: true

# Enable IGWN-alert overseer
alerts:
  igwn: true

# Change according to your cluster settings
storageClassName: &storage_class "standard"

# Only relevant for "distributed" deployment
#storageClassNameRWX: ""

# Database configuration valid for both single node
#   and distributed configurations.
database:
  name: &database_name gracedb
  user: &database_user gracedb
  storageCapacity: &database_storage_capacity 10Gi
  # This is only relevant for the distributed deployment strategy
  #readReplicas: &database_read_replicas 2

# Required for Ingress
# This name should be resolved by your browser,
# so if it's not a valid DNS name
# it should go in the /etc/hosts file
# i.e. for Minikube you can get the VM ip by running:
# minikube ip -p <profile_name>
publicName: gracedb.default.svc.cluster.local

tier:
  # Uses the 'generic-test' configuration
  # Sentry environment name
  sentryEnvironment: "generic-test"
  settingModule: "config.settings.container.generic-test"
  supportContact: "albert.einstein@ligo.org"

gracedb:
  image: "containers.ligo.org/computing/gracedb/server:gracedb-2.29.0"
  storage:
    capacity: 10Gi
  resources:
    cpu: 2
    memory: 8Gi
  # This is for Django admin user
  djangoSuperuserName: "admin"
  djangoSuperuserEmail: "albert.einstein@ligo.org"
  # This is for the Hop server
  igwnAlertAuth: false
  igwnAlertServer: "hopskotch"
  igwnAlertGroup: "default"
  # Only relevant for "distributed" deployment
  #replicaCount: 3
  #pvcName: ""

# If disabled, secrtes should be created 
# before installing the chart
secrets:
  enabled: true
  # Secret named after the release (e.g. gracedb)
  djangoSecretKey: "verylongstring"
  djangoSuperuserPassword: "mypassword"
  dbPassword: "dbpassword"
  # Secret named 'igwn-alert-credentials'
  #  --- igwnAlertUsername: ""
  #  --- igwnAlertPassword: ""
  # Secret named 'shibboleth-key'
  #  --- shibbolethCert: ""
  #  --- shibbolethPKey: ""

# This is for single instance DB architecture
postgres:
  image: "postgres:16.2"
  resources:
    cpu: 0.5
    memory: 1Gi

## CONFIGURATION FOR SUBCHARTS
cert-manager:
  installCRDs: true

# This is for replicated DB architecture (uses an external Helm chart)
#postgresql:
#  architecture: replication
#  auth:
#    username: *database_user
#    database: *database_name
#    existingSecret: ""
#    secretKeys:
#      adminPasswordKey: ""
#      userPasswordKey: ""
#      replicationPasswordKey: ""
#  primary:
#    persistence:
#      size: *database_storage_capacity
#      storageClass: *storage_class
#    resources:
#      requests:
#        cpu: 1
#        memory: 1Gi
#      limits:
#        cpu: 1
#        memory: 1Gi
#  readReplicas:
#    replicaCount: *database_read_replicas
#    persistence:
#      size: *database_storage_capacity
#      storageClass: *storage_class
#    resources:
#      requests:
#        cpu: 1
#        memory: 1Gi
#      limits:
#        cpu: 1
#        memory: 1Gi

memcached:
  replicaCount: 1
  resources:
    requests:
      cpu: 0.1
      memory: 100Mi
    limits:
      cpu: 0.1
      memory: 100Mi

