{{- if and .Values.secrets.enabled  .Values.gracedb.igwnAlertAuth}}
apiVersion: v1
kind: Secret
metadata:
  name: igwn-alert-credentials
data:
  IGWN_ALERT_USER: {{ .Values.secrets.igwnAlertUsername | b64enc }}
  IGWN_ALERT_PASSWORD: {{ .Values.secrets.igwnAlertPassword | b64enc }}
{{- end }}
