{{- if and .Values.secrets.enabled (not .Values.sandboxed.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: shibboleth-key
data:
  sp-cert.pem: |
    {{- .Values.secrets.shibbolethCert | b64enc | nindent 4 }}
  sp-key.pem: |
    {{- .Values.secrets.shibbolethPKey | b64enc | nindent 4 }}
{{- end }}
